services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 85:80
    depends_on:
      - api
    networks:
      - secureshare_network
    restart: always
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./app:/secureshare/app
      - ./config:/secureshare/config
      - ./database:/secureshare/database
      - ./public:/secureshare/public
      - ./tests:/secureshare/tests
      - ./docker/api/php/conf.d/error_logging.ini:/usr/local/etc/php/conf.d/error_logging.ini:ro
      - ./docker/api/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./docker/api/xdebug/tmp/xdebug.log:/tmp/xdebug.log
    restart: always
    environment:
      - DB_HOST=mariadb
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_NAME=${MARIADB_DATABASE}
      - DB_PORT=${MARIADB_PORT}
      - DB_DRIVER=${DB_DRIVER}
      - XDEBUG_MODE=${XDEBUG_MODE}
    depends_on:
      - mariadb
      - cache
    networks:
      - secureshare_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mariadb:
    image: mariadb:lts
    volumes:
      - secureshare_mariadb_volume:/var/lib/mysql
    restart: "always"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
    networks:
      - secureshare_network
  cache:
    image: redis:latest
    networks:
      - secureshare_network
    restart: always
volumes:
  secureshare_mariadb_volume:
networks:
  secureshare_network:
    driver: bridge